pipeline:
  name: Delete Vultr Cluster
  identifier: Delete_Vultr_Cluster
  projectIdentifier: SBrooksChallenge
  orgIdentifier: EVT
  tags: {}
  stages:
    - stage:
        name: Delete Vultr Cluster
        identifier: Delete_Vultr_Cluster
        type: CI
        spec:
          cloneCodebase: false
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.sbrooks
              namespace: harness-builds
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Delete Cluster
                  identifier: Delete_Cluster
                  spec:
                    connectorRef: account.Tesin_DockerHub
                    image: ubuntu
                    shell: Bash
                    command: |-
                      #!/bin/bash

                      # This script expects the CLUSTER_ID to come from an environment variable.

                      API_ENDPOINT="https://api.vultr.com/v2/kubernetes/clusters/${CLUSTER_ID}"

                      apt-get update && apt-get install -y curl

                      curl ${API_ENDPOINT} \
                        -H "Authorization: Bearer ${VULTR_API_KEY}" \
                        -X DELETE
                    envVariables:
                      VULTR_API_KEY: <+secrets.getValue("VULTR_API_KEY")>
                      CLUSTER_ID: <+input>
        variables: []
