apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "evt-challenge.fullname" . }}-neo4j
  labels:
    {{- include "evt-challenge.labels" . | nindent 4 }}
spec:
  {{- if not .Values.neo4j.autoscaling.enabled }}
  replicas: {{ .Values.neo4j.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "evt-challenge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.neo4j.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "evt-challenge.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.neo4j.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "evt-challenge.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.neo4j.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.neo4j.securityContext | nindent 12 }}
          image: "{{ .Values.neo4j.image.repository }}:{{ .Values.neo4j.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.neo4j.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 7474
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.neo4j.resources | nindent 12 }}
      {{- with .Values.neo4j.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.neo4j.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.neo4j.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}