apiVersion: v1
kind: Service

metadata:
  name: evt-lb
  annotations:
    service.beta.kubernetes.io/vultr-loadbalancer-protocol: 'http'

spec:
  type: LoadBalancer
  selector:
    name: webapp
  ports:
    - name: http
      port: 80
      targetPort: 3000
